apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "technical-interview-frontend.fullname" . }}-config
  labels:
    {{- include "technical-interview-frontend.labels" . | nindent 4 }}
data:
  FRONTEND_API_UPSTREAM: {{ .Values.config.apiUpstream | quote }}
