version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-runtime-dependencies:
        dependency-type: production
        patterns:
          - "*"
      npm-tooling-test-dependencies:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions-updates:
        patterns:
          - "*"
