apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: technical-interview-frontend
resources:
  - ../../base
patches:
  - path: patch-configmap.yaml
  - path: patch-deployment.yaml
  - path: patch-horizontalpodautoscaler.yaml
