apiVersion: v1
kind: ConfigMap
metadata:
  name: technical-interview-frontend-config
  namespace: technical-interview-frontend
  labels:
    app.kubernetes.io/name: technical-interview-frontend
    app.kubernetes.io/component: frontend
data:
  FRONTEND_API_UPSTREAM: "http://technical-interview-demo.technical-interview-demo.svc.cluster.local:80"
