apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: technical-interview-frontend
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - horizontalpodautoscaler.yaml
  - poddisruptionbudget.yaml
  - service.yaml
images:
  - name: technical-interview-frontend
    newName: ghcr.io/example/technical-interview-frontend
    newTag: latest
